import { collection, doc, getDoc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc, writeBatch } from "firebase/firestore";
import { requireDb } from "@/lib/firebase";
import type { AppNotification, SettlementAllocation, SettlementRequest } from "@/types";

export function subscribeNotifications(uid:string,next:(items:AppNotification[])=>void,fail:(error:Error)=>void){return onSnapshot(query(collection(requireDb(),"users",uid,"notifications"),orderBy("createdAt","desc")),snapshot=>next(snapshot.docs.map(item=>({id:item.id,...item.data()}) as AppNotification)),fail)}
export async function markNotificationRead(uid:string,id:string){await updateDoc(doc(requireDb(),"users",uid,"notifications",id),{read:true})}
export async function markAllNotificationsRead(uid:string,items:AppNotification[]){const unread=items.filter(item=>!item.read);if(!unread.length)return;const db=requireDb(),batch=writeBatch(db);unread.forEach(item=>batch.update(doc(db,"users",uid,"notifications",item.id),{read:true}));await batch.commit()}
export async function requestPayment(input:{requesterUid:string;approverUid:string;requesterName:string;approverName:string;allocations:SettlementAllocation[]}){
 const db=requireDb(), signature=input.allocations.map(a=>`${a.folderId}_${a.contributionId}_${a.fromFriendId}_${a.toFriendId}`).sort().join("__"), ref=doc(db,"settlementRequests",`${input.requesterUid}_${input.approverUid}_${signature}`), amount=Math.abs(input.allocations.reduce((sum,item)=>sum+(item.fromFriendId==="me"?item.amount:-item.amount),0)), batch=writeBatch(db), existing=await getDoc(ref);
 if(existing.exists()&&existing.data().status==="pending") throw new Error("A confirmation request for these contributions is already pending.");
 batch.set(ref,{...input,amount,requestedAction:"paid",status:"pending",createdAt:serverTimestamp(),respondedAt:null,disapprovalReason:null});
 batch.set(doc(collection(db,"users",input.approverUid,"notifications")),{type:"payment-approval-request",title:"Payment Confirmation",message:`${input.requesterName} says they paid you ${amount.toLocaleString("en-PH",{style:"currency",currency:"PHP"})}.`,actorUid:input.requesterUid,recipientUid:input.approverUid,settlementRequestId:ref.id,read:false,createdAt:serverTimestamp()});
 batch.set(doc(collection(db,"users",input.requesterUid,"notifications")),{type:"payment-pending",title:"Payment Pending",message:`Waiting for ${input.approverName} to confirm your payment.`,actorUid:input.requesterUid,recipientUid:input.requesterUid,settlementRequestId:ref.id,read:false,createdAt:serverTimestamp()});
 await batch.commit(); return ref.id;
}
export function subscribeSettlementRequest(id:string,next:(value:SettlementRequest|null)=>void,fail:(error:Error)=>void){return onSnapshot(doc(requireDb(),"settlementRequests",id),snap=>next(snap.exists()?({id:snap.id,...snap.data()}) as SettlementRequest:null),fail)}
export async function respondPaymentRequest(uid:string,request:SettlementRequest,approve:boolean,reason=""){
 const db=requireDb(), requestRef=doc(db,"settlementRequests",request.id);
 await runTransaction(db,async tx=>{const current=await tx.get(requestRef);if(!current.exists()||current.data().status!=="pending"||current.data().approverUid!==uid)throw new Error("This request is no longer available.");const refs=request.allocations.map(a=>doc(db,"users",request.requesterUid,"settlements",`${a.folderId}_${a.contributionId}_${a.fromFriendId}_${a.toFriendId}`)), previous=approve?await Promise.all(refs.map(ref=>tx.get(ref))):[], now=serverTimestamp();if(approve)request.allocations.forEach((a,index)=>{const old=previous[index], prior=old.exists()?Number(old.data().amount||0):0;if(Math.round(prior*100)!==Math.round(Number(a.expectedPreviouslySettled||0)*100))throw new Error(`The balance for ${a.contributionTitle} changed. Recalculate this person's settlement.`);tx.set(refs[index],{folderId:a.folderId,contributionId:a.contributionId,fromFriendId:a.fromFriendId,toFriendId:a.toFriendId,amount:prior+a.amount,source:"paid-approved",status:"completed",initiatedByUserId:request.requesterUid,approvedByUserId:uid,executedByUserId:request.requesterUid,requestId:request.id,date:now,createdAt:old.exists()?old.data().createdAt:now,updatedAt:now},{merge:true})});tx.update(requestRef,{status:approve?"approved":"disapproved",respondedAt:now,disapprovalReason:reason||null});tx.set(doc(collection(db,"users",request.requesterUid,"notifications")),{type:approve?"payment-approved":"payment-disapproved",title:approve?"Payment Approved":"Payment Disapproved",message:approve?`${request.approverName} confirmed receiving your payment.`:`${request.approverName} did not confirm your payment.${reason?` ${reason}`:""}`,actorUid:uid,recipientUid:request.requesterUid,settlementRequestId:request.id,read:false,createdAt:now});});
}
export async function cancelPaymentRequest(uid:string,request:SettlementRequest){if(request.requesterUid!==uid)throw new Error("Only the requester can cancel this request.");await updateDoc(doc(requireDb(),"settlementRequests",request.id),{status:"cancelled",respondedAt:serverTimestamp()})}
export async function notifyReceived(actorUid:string,recipientUid:string,actorName:string,amount:number){const db=requireDb();await writeBatch(db).set(doc(collection(db,"users",recipientUid,"notifications")),{type:"payment-received-recorded",title:"Payment Recorded",message:`${actorName} confirmed receiving ${amount.toLocaleString("en-PH",{style:"currency",currency:"PHP"})} from you.`,actorUid,recipientUid,read:false,createdAt:serverTimestamp()}).commit()}
