"use client";
import Link from "next/link"; import { useRouter } from "next/navigation"; import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/Button"; import { Field } from "@/components/ui/Field"; import { Notice } from "@/components/ui/Feedback"; import { useAuth } from "@/hooks/useAuth";
export function AuthForm({ mode }: { mode: "login" | "register" }) { const auth = useAuth(); const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const isRegister = mode === "register";
  useEffect(() => { if (!auth.loading && auth.currentUser) router.replace("/"); }, [auth.loading, auth.currentUser, router]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const data = new FormData(event.currentTarget); try { if (isRegister) await auth.register(String(data.get("name")), String(data.get("email")), String(data.get("password"))); else await auth.login(String(data.get("email")), String(data.get("password"))); router.replace("/"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to continue."); } finally { setBusy(false); } }
  async function google() { setBusy(true); setError(null); try { await auth.loginWithGoogle(); router.replace("/"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Google sign-in failed."); setBusy(false); } }
  return <section className="auth-card"><h2>{isRegister ? "Create your account" : "Welcome back"}</h2><p>{isRegister ? "Start organizing shared costs with your people." : "Sign in to continue to your folders."}</p><Notice message={error || auth.error} /><form onSubmit={submit}>{isRegister && <Field label="Display name" name="name" autoComplete="name" autoFocus required maxLength={80} />}<Field label="Email" name="email" type="email" autoComplete="email" required /><Field label="Password" name="password" type="password" autoComplete={isRegister ? "new-password" : "current-password"} required minLength={6} /><Button disabled={busy}>{busy ? "Please wait…" : isRegister ? "Create account" : "Sign in"}</Button></form><div className="divider"><span>or</span></div><Button type="button" variant="secondary" onClick={google} disabled={busy}>Continue with Google</Button><p className="auth-switch">{isRegister ? "Already have an account?" : "New to AmbagGabay?"} <Link href={isRegister ? "/login" : "/register"}>{isRegister ? "Sign in" : "Create one"}</Link></p></section>;
}
