import type { ContributionObligation, ContributionWithExpenses, Settlement, SettlementDirection } from "@/types";
export const toCentavos = (amount: number) => Math.round(amount * 100);
export const fromCentavos = (amount: number) => amount / 100;
export const formatMoney = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", minimumFractionDigits: 2 }).format(amount);
export type FinancialDirection = "incoming" | "outgoing" | "neutral";
export function getFinancialDirection(fromId: string, toId: string, currentId = "me"): FinancialDirection { return toId === currentId ? "incoming" : fromId === currentId ? "outgoing" : "neutral"; }
export const moneyDirectionClass = (fromId: string, toId: string, currentId = "me") => `money-${getFinancialDirection(fromId, toId, currentId)}`;
export function splitCentavos(amount: number, participantIds: string[]) { const ids = [...new Set(participantIds)].sort(); if (!ids.length) return new Map<string, number>(); const cents = toCentavos(amount); const base = Math.floor(cents / ids.length); const remainder = cents - base * ids.length; return new Map(ids.map((id, index) => [id, base + (index < remainder ? 1 : 0)])); }
export function contributionRoundedShares(contribution: ContributionWithExpenses) { const rawShares = new Map<string, number>(); for (const expense of contribution.expenses) { const ids = [...new Set(expense.participantIds)]; if (!ids.length) continue; const rawShare = toCentavos(expense.amount) / ids.length; for (const id of ids) rawShares.set(id, (rawShares.get(id) || 0) + rawShare); } return new Map([...rawShares].map(([id, rawCentavos]) => [id, Math.ceil(rawCentavos - 1e-9)])); }
function contributionPaid(contribution: ContributionWithExpenses) { const paid = new Map<string, number>(); for (const expense of contribution.expenses) { const payer = effectiveExpensePayer(contribution, expense); paid.set(payer, (paid.get(payer) || 0) + toCentavos(expense.amount)); } return paid; }
export function contributionSettlementAnchor(contribution: ContributionWithExpenses) { return contribution.settlementAnchorFriendId || (contribution.participantIds.includes("me") ? "me" : contribution.payerFriendId); }
function centralizedContributionDirections(contribution: ContributionWithExpenses): SettlementDirection[] { const anchor = contributionSettlementAnchor(contribution), shares = contributionRoundedShares(contribution), paid = contributionPaid(contribution), ids = new Set([...shares.keys(), ...paid.keys()]); return [...ids].filter(id => id !== anchor).flatMap(id => { const difference = (shares.get(id) || 0) - (paid.get(id) || 0); if (difference > 0) return [{ fromFriendId: id, toFriendId: anchor, amount: fromCentavos(difference) }]; if (difference < 0) return [{ fromFriendId: anchor, toFriendId: id, amount: fromCentavos(-difference) }]; return []; }); }
export const contributionTotal = (value: ContributionWithExpenses) => fromCentavos(value.expenses.reduce((sum, item) => sum + toCentavos(item.amount), 0));
export const effectiveExpensePayer = (contribution: ContributionWithExpenses, expense: ContributionWithExpenses["expenses"][number]) => expense.payerFriendId || contribution.payerFriendId;
export function calculateBalances(contributions: ContributionWithExpenses[], settlements: Settlement[] = []) { const paid = new Map<string, number>(), shares = new Map<string, number>(), balances = new Map<string, number>(); for (const contribution of contributions) { for (const [id, cents] of contributionPaid(contribution)) paid.set(id, (paid.get(id) || 0) + cents); for (const [id, cents] of contributionRoundedShares(contribution)) shares.set(id, (shares.get(id) || 0) + cents); } for (const obligation of contributionObligations(contributions, settlements)) { const cents = toCentavos(obligation.amount); balances.set(obligation.fromFriendId, (balances.get(obligation.fromFriendId) || 0) - cents); balances.set(obligation.toFriendId, (balances.get(obligation.toFriendId) || 0) + cents); } const ids = new Set([...paid.keys(), ...shares.keys(), ...balances.keys()]); return [...ids].map(id => ({ friendId: id, paid: fromCentavos(paid.get(id) || 0), share: fromCentavos(shares.get(id) || 0), balance: fromCentavos(balances.get(id) || 0) })); }
export function settlementDirections(contributions: ContributionWithExpenses[], settlements: Settlement[] = []): SettlementDirection[] { return contributionObligations(contributions, settlements).map(({ fromFriendId, toFriendId, amount }) => ({ fromFriendId, toFriendId, amount })); }
export function contributionFriendPosition(contribution: ContributionWithExpenses, friendId: string) { const share = contributionRoundedShares(contribution).get(friendId) || 0, paid = contributionPaid(contribution).get(friendId) || 0; let netEffect = 0; for (const direction of centralizedContributionDirections(contribution)) { const cents = toCentavos(direction.amount); if (direction.fromFriendId === friendId) netEffect += cents; if (direction.toFriendId === friendId) netEffect -= cents; } return { share: fromCentavos(share), paid: fromCentavos(paid), netEffect: fromCentavos(netEffect) }; }
export function contributionObligations(contributions: ContributionWithExpenses[], settlements: Settlement[] = []): ContributionObligation[] {
  const obligations = contributions.flatMap(contribution => centralizedContributionDirections(contribution).map(flow => ({ ...flow, contributionId: contribution.id, contributionTitle: contribution.title, contributionDate: contribution.date, grossAmount: flow.amount, settledAmount: 0 })));
  for (const settlement of settlements.filter(item => item.contributionId)) {
    let remaining = toCentavos(settlement.amount);
    const matches = obligations.filter(item => item.fromFriendId === settlement.fromFriendId && item.toFriendId === settlement.toFriendId && (!settlement.contributionId || item.contributionId === settlement.contributionId));
    for (const item of matches) { const available = toCentavos(item.amount); const applied = Math.min(available, remaining); item.amount = fromCentavos(available - applied); item.settledAmount = fromCentavos(toCentavos(item.settledAmount) + applied); remaining -= applied; if (!remaining) break; }
    // A pre-2.6 settlement may have paid a secondary payer directly. Preserve that
    // history by treating it as simultaneously reducing the participant→anchor
    // debt and the matching anchor→secondary-payer reimbursement.
    if (remaining && settlement.contributionId) {
      const debtor = obligations.find(item => item.contributionId === settlement.contributionId && item.fromFriendId === settlement.fromFriendId),
        creditor = obligations.find(item => item.contributionId === settlement.contributionId && item.toFriendId === settlement.toFriendId);
      if (debtor && creditor && debtor !== creditor) {
        const applied = Math.min(remaining, toCentavos(debtor.amount), toCentavos(creditor.amount));
        for (const item of [debtor, creditor]) { item.amount = fromCentavos(toCentavos(item.amount) - applied); item.settledAmount = fromCentavos(toCentavos(item.settledAmount) + applied); }
      }
    }
  }
  return obligations.filter(item => toCentavos(item.amount) > 0);
}
export interface PairNetBalance { personId:string; counterpartyId:string; incomingCentavos:number; outgoingCentavos:number; netCentavos:number }
export function getPairNetBalance(contributions:ContributionWithExpenses[],settlements:Settlement[],personId:string,counterpartyId:string):PairNetBalance { let incomingCentavos=0,outgoingCentavos=0;for(const obligation of contributionObligations(contributions,settlements)){const cents=toCentavos(obligation.amount);if(obligation.fromFriendId===counterpartyId&&obligation.toFriendId===personId)incomingCentavos+=cents;else if(obligation.fromFriendId===personId&&obligation.toFriendId===counterpartyId)outgoingCentavos+=cents}return{personId,counterpartyId,incomingCentavos,outgoingCentavos,netCentavos:incomingCentavos-outgoingCentavos} }
export interface ActivePairRelationship { fromFriendId:string;toFriendId:string;amountCentavos:number }
export function getActivePairRelationships(contributions:ContributionWithExpenses[],settlements:Settlement[]=[]):ActivePairRelationship[]{const pairs=new Map<string,{a:string;b:string;aReceives:number;bReceives:number}>();for(const obligation of contributionObligations(contributions,settlements)){const [a,b]=[obligation.fromFriendId,obligation.toFriendId].sort(),key=`${a}\u0000${b}`,pair=pairs.get(key)||{a,b,aReceives:0,bReceives:0},cents=toCentavos(obligation.amount);if(obligation.toFriendId===a)pair.aReceives+=cents;else pair.bReceives+=cents;pairs.set(key,pair)}return[...pairs.values()].flatMap(pair=>{const net=pair.aReceives-pair.bReceives;if(!net)return[];return net>0?[{fromFriendId:pair.b,toFriendId:pair.a,amountCentavos:net}]:[{fromFriendId:pair.a,toFriendId:pair.b,amountCentavos:-net}]})}
export const folderTotal = (contributions: ContributionWithExpenses[]) => fromCentavos(contributions.reduce((sum, contribution) => sum + contribution.expenses.reduce((expenseSum, expense) => expenseSum + toCentavos(expense.amount), 0), 0));
