import type { ContributionObligation, ContributionWithExpenses, Settlement, SettlementDirection } from "@/types";
export const toCentavos = (amount: number) => Math.round(amount * 100);
export const fromCentavos = (amount: number) => amount / 100;
export const formatMoney = (amount: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", minimumFractionDigits: 2 }).format(amount);
export function splitCentavos(amount: number, participantIds: string[]) { const ids = [...new Set(participantIds)].sort(); if (!ids.length) return new Map<string, number>(); const cents = toCentavos(amount); const base = Math.floor(cents / ids.length); const remainder = cents - base * ids.length; return new Map(ids.map((id, index) => [id, base + (index < remainder ? 1 : 0)])); }
export const contributionTotal = (value: ContributionWithExpenses) => fromCentavos(value.expenses.reduce((sum, item) => sum + toCentavos(item.amount), 0));
export const effectiveExpensePayer = (contribution: ContributionWithExpenses, expense: ContributionWithExpenses["expenses"][number]) => expense.payerFriendId || contribution.payerFriendId;
export function calculateBalances(contributions: ContributionWithExpenses[], settlements: Settlement[] = []) { const paid = new Map<string, number>(); const shares = new Map<string, number>(); const adjustments = new Map<string, number>(); for (const contribution of contributions) for (const expense of contribution.expenses) { const payer = effectiveExpensePayer(contribution, expense); paid.set(payer, (paid.get(payer) || 0) + toCentavos(expense.amount)); for (const [id, cents] of splitCentavos(expense.amount, expense.participantIds)) shares.set(id, (shares.get(id) || 0) + cents); } for (const settlement of settlements) { const cents = toCentavos(settlement.amount); adjustments.set(settlement.fromFriendId, (adjustments.get(settlement.fromFriendId) || 0) + cents); adjustments.set(settlement.toFriendId, (adjustments.get(settlement.toFriendId) || 0) - cents); } const ids = new Set([...paid.keys(), ...shares.keys(), ...adjustments.keys()]); return [...ids].map(id => ({ friendId: id, paid: fromCentavos(paid.get(id) || 0), share: fromCentavos(shares.get(id) || 0), balance: fromCentavos((paid.get(id) || 0) - (shares.get(id) || 0) + (adjustments.get(id) || 0)) })); }
export function settlementDirections(contributions: ContributionWithExpenses[], settlements: Settlement[] = []): SettlementDirection[] { const balances = calculateBalances(contributions, settlements).map(item => ({ id: item.friendId, cents: toCentavos(item.balance) })); const debtors = balances.filter(item => item.cents < 0).map(item => ({ ...item, cents: -item.cents })).sort((a,b) => b.cents-a.cents); const creditors = balances.filter(item => item.cents > 0).sort((a,b) => b.cents-a.cents); const directions: SettlementDirection[] = []; let di=0,ci=0; while(di<debtors.length&&ci<creditors.length){const cents=Math.min(debtors[di].cents,creditors[ci].cents);if(cents>0)directions.push({fromFriendId:debtors[di].id,toFriendId:creditors[ci].id,amount:fromCentavos(cents)});debtors[di].cents-=cents;creditors[ci].cents-=cents;if(!debtors[di].cents)di++;if(!creditors[ci].cents)ci++;} return directions; }
export function contributionFriendPosition(contribution: ContributionWithExpenses, friendId: string) { let share = 0, paid = 0; for (const expense of contribution.expenses) { share += splitCentavos(expense.amount, expense.participantIds).get(friendId) || 0; if (effectiveExpensePayer(contribution, expense) === friendId) paid += toCentavos(expense.amount); } return { share: fromCentavos(share), paid: fromCentavos(paid), netEffect: fromCentavos(share - paid) }; }
export function contributionObligations(contributions: ContributionWithExpenses[], settlements: Settlement[] = []): ContributionObligation[] {
  const obligations = contributions.flatMap(contribution => settlementDirections([contribution]).map(flow => ({ ...flow, contributionId: contribution.id, contributionTitle: contribution.title, contributionDate: contribution.date, grossAmount: flow.amount, settledAmount: 0 })));
  for (const settlement of settlements) {
    let remaining = toCentavos(settlement.amount);
    const matches = obligations.filter(item => item.fromFriendId === settlement.fromFriendId && item.toFriendId === settlement.toFriendId && (!settlement.contributionId || item.contributionId === settlement.contributionId));
    for (const item of matches) { const available = toCentavos(item.amount); const applied = Math.min(available, remaining); item.amount = fromCentavos(available - applied); item.settledAmount = fromCentavos(toCentavos(item.settledAmount) + applied); remaining -= applied; if (!remaining) break; }
  }
  return obligations.filter(item => toCentavos(item.amount) > 0);
}
export const folderTotal = (contributions: ContributionWithExpenses[]) => fromCentavos(contributions.reduce((sum, contribution) => sum + contribution.expenses.reduce((expenseSum, expense) => expenseSum + toCentavos(expense.amount), 0), 0));
