"use client";
import { useMemo, useState } from "react";
import { Dialog } from "@/components/ui/Dialog";
import { Button } from "@/components/ui/Button";
import { Notice } from "@/components/ui/Feedback";
import type { FolderFinancials, Friend } from "@/types";
import { contributionObligations, formatMoney, toCentavos } from "@/utils/money";
import { recordSettlement } from "@/services/settlements";
import { notifyReceived, requestPayment } from "@/services/notifications";

export function SettlePaymentsDialog({open,onClose,uid,userName,friends,financials,folderId,preselectedFriendId,onComplete}:{open:boolean;onClose:()=>void;uid:string;userName:string;friends:Friend[];financials:FolderFinancials[];folderId?:string;preselectedFriendId?:string;onComplete?:()=>Promise<void>|void}){
 const [friendId,setFriendId]=useState(preselectedFriendId||""),[selected,setSelected]=useState<string[]>([]),[calculated,setCalculated]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const scoped=folderId?financials.filter(item=>item.folder.id===folderId):financials;
 const entries=useMemo(()=>scoped.flatMap(folder=>contributionObligations(folder.contributions,folder.settlements).filter(item=>(item.fromFriendId==="me"&&item.toFriendId===friendId)||(item.toFriendId==="me"&&item.fromFriendId===friendId)).map(item=>({folder,friend:friends.find(value=>value.id===friendId)!,allocation:{folderId:folder.folder.id,contributionId:item.contributionId,fromFriendId:item.fromFriendId,toFriendId:item.toFriendId,amount:item.amount,contributionTitle:item.contributionTitle}}))).filter(item=>item.friend),[scoped,friendId,friends]);
 const chosen=entries.filter(item=>selected.includes(`${item.folder.folder.id}-${item.allocation.contributionId}-${item.allocation.fromFriendId}`)),receivable=chosen.filter(item=>item.allocation.toFriendId==="me").reduce((sum,item)=>sum+toCentavos(item.allocation.amount),0),payable=chosen.filter(item=>item.allocation.fromFriendId==="me").reduce((sum,item)=>sum+toCentavos(item.allocation.amount),0),net=receivable-payable,person=friends.find(item=>item.id===friendId);
 const reset=()=>{setFriendId(preselectedFriendId||"");setSelected([]);setCalculated(false);setMessage(null);onClose()};
 async function finalize(){if(!person||!chosen.length)return;setBusy(true);setMessage(null);try{if(net<0&&person.linkedUserId){await requestPayment({requesterUid:uid,approverUid:person.linkedUserId,requesterName:userName,approverName:person.name,allocations:chosen.map(item=>item.allocation)});setMessage(`Payment confirmation requested from ${person.name}. The balance remains outstanding until approval.`);setCalculated(false);return}for(const item of chosen)await recordSettlement(uid,{...item.allocation,expectedPreviouslySettled:item.folder.settlements.find(s=>s.contributionId===item.allocation.contributionId&&s.fromFriendId===item.allocation.fromFriendId&&s.toFriendId===item.allocation.toFriendId)?.amount||0,source:person.linkedUserId&&net>0?"received":"nonlinked-executory",description:`Settlement recorded · ${item.allocation.contributionTitle}`,executedByUserId:uid});if(person.linkedUserId&&net>0)await notifyReceived(uid,person.linkedUserId,userName,Math.abs(net)/100);await onComplete?.();setMessage("Settlement recorded.");setCalculated(false);setSelected([])}catch(cause){setMessage(cause instanceof Error?cause.message:"Unable to record settlement.")}finally{setBusy(false)}}
 return <Dialog open={open} wide title="Settle Payments" onClose={reset}><div className="settle-workflow"><div className="step-indicator"><strong>1. Person</strong><strong>2. Contributions</strong><strong>3. Result</strong></div><Notice message={message} tone={message?.includes("recorded")?"success":"error"}/><label className="field">Who do you want to settle with?<select value={friendId} onChange={e=>{setFriendId(e.target.value);setSelected([]);setCalculated(false)}}><option value="">Select a person</option>{friends.filter(item=>item.id!=="me"&&!item.archived).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{person&&<><div className="settlement-contributions">{entries.map(entry=>{const key=`${entry.folder.folder.id}-${entry.allocation.contributionId}-${entry.allocation.fromFriendId}`;return <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={()=>{setSelected(values=>values.includes(key)?values.filter(value=>value!==key):[...values,key]);setCalculated(false)}}/><span><strong>{entry.allocation.contributionTitle}</strong><small>{entry.folder.folder.name} · {entry.allocation.fromFriendId==="me"?`You need to pay ${formatMoney(entry.allocation.amount)}`:`You should receive ${formatMoney(entry.allocation.amount)}`}</small></span></label>})}</div>{entries.length>0&&<Button variant="ghost" onClick={()=>{setSelected(entries.map(entry=>`${entry.folder.folder.id}-${entry.allocation.contributionId}-${entry.allocation.fromFriendId}`));setCalculated(false)}}>Select All Outstanding</Button>}<div className="summary-grid"><article className="metric"><span>Receivable</span><strong>{formatMoney(receivable/100)}</strong></article><article className="metric"><span>Payable</span><strong>{formatMoney(payable/100)}</strong></article></div>{!calculated?<Button disabled={!chosen.length} onClick={()=>setCalculated(true)}>Calculate</Button>:<section className="settlement-result"><h3>Settlement Result</h3><div className="calculation-breakdown">{chosen.map(item=><div key={`${item.folder.folder.id}-${item.allocation.contributionId}-${item.allocation.fromFriendId}`}><span>{item.allocation.contributionTitle}<small>{item.allocation.fromFriendId==="me"?`You → ${person.name}`:`${person.name} → You`}</small></span><strong>{item.allocation.fromFriendId==="me"?"−":"+"}{formatMoney(item.allocation.amount)}</strong></div>)}</div><h2>{net===0?"No payment is needed":net>0?`You should receive ${formatMoney(net/100)} from ${person.name}`:`You need to pay ${formatMoney(-net/100)} to ${person.name}`}</h2><div className="dialog-actions"><Button variant="secondary" onClick={()=>setCalculated(false)}>Back</Button><span/>{net!==0&&<Button disabled={busy} onClick={finalize}>{net>0?"Received":"Paid"}</Button>}</div></section>}</>}</div></Dialog>
}
