"use client";
import Link from "next/link"; import { useCallback, useState, type FormEvent } from "react"; import { MoreHorizontal, Plus } from "lucide-react";
import { Button } from "@/components/ui/Button"; import { Dialog } from "@/components/ui/Dialog"; import { EmptyState, LoadingState, Notice } from "@/components/ui/Feedback"; import { Field, SelectField } from "@/components/ui/Field"; import { PageHeader } from "@/components/ui/PageHeader"; import { useAuth } from "@/hooks/useAuth"; import { useCollectionData } from "@/hooks/useCollectionData"; import { subscribeFriendGroups } from "@/services/friendGroups"; import { createFolder, deleteFolder, subscribeFolders, updateFolder } from "@/services/folders"; import type { Folder } from "@/types";
const icons = ["📁", "✈️", "🍽️", "🏠", "🎉", "🛒", "🏖️"];
export default function DashboardPage() { const { currentUser } = useAuth(); const uid = currentUser?.uid; const folderSub = useCallback((next: Parameters<typeof subscribeFolders>[1], fail: Parameters<typeof subscribeFolders>[2]) => subscribeFolders(uid!, next, fail), [uid]); const groupSub = useCallback((next: Parameters<typeof subscribeFriendGroups>[1], fail: Parameters<typeof subscribeFriendGroups>[2]) => subscribeFriendGroups(uid!, next, fail), [uid]); const folders = useCollectionData(uid ? folderSub : null); const groups = useCollectionData(uid ? groupSub : null); const [editing, setEditing] = useState<Folder | "new" | null>(null); const [deleting, setDeleting] = useState<Folder | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(null); const data = new FormData(event.currentTarget); const input = { name: String(data.get("name")), icon: String(data.get("icon")), defaultFriendGroupId: String(data.get("group")) || null }; try { if (editing === "new") await createFolder(uid!, input); else if (editing) await updateFolder(uid!, editing.id, input); setEditing(null); setMessage(editing === "new" ? "Folder created." : "Folder updated."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Unable to save folder."); } finally { setBusy(false); } }
  async function remove() { if (!deleting) return; setBusy(true); try { await deleteFolder(uid!, deleting.id); setDeleting(null); setMessage("Folder deleted."); } catch { setMessage("Unable to delete folder. Please try again."); } finally { setBusy(false); } }
  return <><PageHeader title={`Hi, ${currentUser?.displayName?.split(" ")[0] || "there"}`} description="Keep every shared expense organized by occasion." action={<Button onClick={() => setEditing("new")}><Plus size={18} /> New folder</Button>} /><Notice message={folders.error || groups.error || message} tone={message?.includes("created") || message?.includes("updated") || message?.includes("deleted") ? "success" : "error"} />{folders.loading ? <LoadingState label="Loading folders…" /> : folders.items.length === 0 ? <EmptyState title="No folders yet" description="Create a folder for a trip, meal group, event, or shared activity." action={<Button onClick={() => setEditing("new")}><Plus size={18} /> Create folder</Button>} /> : <div className="folder-grid">{folders.items.map(folder => <article className="folder-card" key={folder.id}><Link href={`/folders/${folder.id}`}><span className="folder-icon">{folder.icon || "📁"}</span><h2>{folder.name}</h2><p>{folder.defaultFriendGroupId ? groups.items.find(group => group.id === folder.defaultFriendGroupId)?.name || "Group unavailable" : "No default group"}</p><small>Ready for contributions in Version 0.2</small></Link><button className="icon-button card-menu" aria-label={`Edit ${folder.name}`} onClick={() => setEditing(folder)}><MoreHorizontal /></button></article>)}</div>}
  <Dialog open={!!editing} title={editing === "new" ? "Create folder" : "Edit folder"} onClose={() => setEditing(null)}><form onSubmit={save} className="dialog-form"><Field label="Folder name" name="name" autoFocus required maxLength={80} defaultValue={editing && editing !== "new" ? editing.name : ""} /><SelectField label="Icon" name="icon" defaultValue={editing && editing !== "new" ? editing.icon : "📁"}>{icons.map(icon => <option key={icon}>{icon}</option>)}</SelectField><SelectField label="Default friend group (optional)" name="group" defaultValue={editing && editing !== "new" ? editing.defaultFriendGroupId || "" : ""}><option value="">None</option>{groups.items.map(group => <option value={group.id} key={group.id}>{group.name}</option>)}</SelectField><div className="dialog-actions">{editing !== "new" && <Button type="button" variant="danger" onClick={() => { setDeleting(editing as Folder); setEditing(null); }}>Delete</Button>}<span /><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save"}</Button></div></form></Dialog>
  <Dialog open={!!deleting} title="Delete folder?" onClose={() => setDeleting(null)}><p>This permanently deletes <strong>{deleting?.name}</strong>. There are no contributions in Version 0.1.</p><div className="dialog-actions"><span /><Button variant="secondary" onClick={() => setDeleting(null)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={remove}>{busy ? "Deleting…" : "Delete folder"}</Button></div></Dialog></>;
}
